environment: pytorch 1.11.0 -> 1.12.1; cuda 11.5 -> 11.6; WIP remove external DCNv2
In addition to the version bump, this should allow us to use the deformable convolution functionality torchvision provides.

Unfortunately, it's not there all the way there yet.

The original implementation (either from the environment file or in-tree) didn't divide the second dimension of the weights attribute by the number of groups, keeping it exactly the number of input channels.

This present a problem for those trying to use the pretrained weights because moving to the built-in variant, which does divide the number of input channels by the number of groups, causes a shape error to be thrown when loading from the checkpoint. As an example, where previously a tensor might have been shaped (64, 64, 3, 3) in the checkpoint, the model would expect it to be (64, 8, 3, 3) since we specify eight groups.

In trying to patch the torchvision source to keep the second dimenion unchanged, I've run into a new error which I have not yet fixed:

```bash
$ python validate.py --n_GPUs 1 --model BSRT --model_level S --swinfeature --batch_size 1 --burst_size 14 --patch_size 80 --pre_train /home/ubuntu/bsrt/models/BSRT_pretrained_models/realworld_models/bsrt_small_realworld.pth --root /home/ubuntu/bsrt/data.vision.ee.ethz.ch/bhatg/BurstSRChallenge
Making model:  BSRT
Patch size:  80
depths:  [6, 6, 6, 6, 6]
using swinfeature
Load the model from /home/ubuntu/bsrt/models/BSRT_pretrained_models/realworld_models/bsrt_small_realworld.pth
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth
  0%|                                                                                                                                                | 0/882 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "validate.py", line 79, in <module>
    main()
  File "validate.py", line 22, in main
    mp.spawn(main_worker, nprocs=1, args=(1, args)) # type: ignore
  File "/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/ubuntu/bsrt/BSRT/code/real/bsrt/validate.py", line 57, in main_worker
    sr = _model(burst, 0).float()
  File "/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/bsrt/BSRT/code/real/bsrt/model/__init__.py", line 59, in forward
    return self.model(x)
  File "/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/ubuntu/bsrt/BSRT/code/real/bsrt/model/bsrt.py", line 572, in forward
    aligned_fea.append(self.align(nbr_fea_l, nbr_warped_l, ref_fea_l, flows_l))
  File "/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/bsrt/BSRT/code/real/bsrt/model/bsrt.py", line 217, in forward
    L3_fea = self.lrelu(self.L3_dcnpack(nbr_fea_l[2], L3_offset, flows_l[2]))
  File "/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/bsrt/BSRT/code/real/bsrt/model/DCNv2/dcn_v2.py", line 331, in forward
    mask,
  File "/home/ubuntu/bsrt/BSRT/code/real/bsrt/model/DCNv2/dcn_v2.py", line 109, in deform_conv2d
    use_mask,
  File "/home/ubuntu/micromamba/envs/bsrt-real/lib/python3.7/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Expected weight_c.size(1) * n_weight_grps == input_c.size(1) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```